/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteScheduleRouteImport } from './routes/_site.schedule'
import { Route as SitePhotosRouteImport } from './routes/_site.photos'
import { Route as SitePartnersRouteImport } from './routes/_site.partners'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteCheckoutRouteImport } from './routes/_site.checkout'
import { Route as SiteCartRouteImport } from './routes/_site.cart'
import { Route as SiteArchiveRouteImport } from './routes/_site.archive'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SitePackagesIndexRouteImport } from './routes/_site.packages.index'
import { Route as SiteTournamentSlugRouteImport } from './routes/_site.tournament.$slug'
import { Route as SitePackagesSlugRouteImport } from './routes/_site.packages.$slug'
import { Route as SiteCheckoutSuccessRouteImport } from './routes/_site.checkout.success'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteScheduleRoute = SiteScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => SiteRoute,
} as any)
const SitePhotosRoute = SitePhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => SiteRoute,
} as any)
const SitePartnersRoute = SitePartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCheckoutRoute = SiteCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCartRoute = SiteCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SiteRoute,
} as any)
const SiteArchiveRoute = SiteArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SitePackagesIndexRoute = SitePackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTournamentSlugRoute = SiteTournamentSlugRouteImport.update({
  id: '/tournament/$slug',
  path: '/tournament/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SitePackagesSlugRoute = SitePackagesSlugRouteImport.update({
  id: '/packages/$slug',
  path: '/packages/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCheckoutSuccessRoute = SiteCheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => SiteCheckoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRoute
  '/join': typeof JoinRoute
  '/about': typeof SiteAboutRoute
  '/archive': typeof SiteArchiveRoute
  '/cart': typeof SiteCartRoute
  '/checkout': typeof SiteCheckoutRouteWithChildren
  '/contact': typeof SiteContactRoute
  '/partners': typeof SitePartnersRoute
  '/photos': typeof SitePhotosRoute
  '/schedule': typeof SiteScheduleRoute
  '/checkout/success': typeof SiteCheckoutSuccessRoute
  '/packages/$slug': typeof SitePackagesSlugRoute
  '/tournament/$slug': typeof SiteTournamentSlugRoute
  '/packages/': typeof SitePackagesIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/join': typeof JoinRoute
  '/about': typeof SiteAboutRoute
  '/archive': typeof SiteArchiveRoute
  '/cart': typeof SiteCartRoute
  '/checkout': typeof SiteCheckoutRouteWithChildren
  '/contact': typeof SiteContactRoute
  '/partners': typeof SitePartnersRoute
  '/photos': typeof SitePhotosRoute
  '/schedule': typeof SiteScheduleRoute
  '/': typeof SiteIndexRoute
  '/checkout/success': typeof SiteCheckoutSuccessRoute
  '/packages/$slug': typeof SitePackagesSlugRoute
  '/tournament/$slug': typeof SiteTournamentSlugRoute
  '/packages': typeof SitePackagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRoute
  '/join': typeof JoinRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/archive': typeof SiteArchiveRoute
  '/_site/cart': typeof SiteCartRoute
  '/_site/checkout': typeof SiteCheckoutRouteWithChildren
  '/_site/contact': typeof SiteContactRoute
  '/_site/partners': typeof SitePartnersRoute
  '/_site/photos': typeof SitePhotosRoute
  '/_site/schedule': typeof SiteScheduleRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/checkout/success': typeof SiteCheckoutSuccessRoute
  '/_site/packages/$slug': typeof SitePackagesSlugRoute
  '/_site/tournament/$slug': typeof SiteTournamentSlugRoute
  '/_site/packages/': typeof SitePackagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/join'
    | '/about'
    | '/archive'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/partners'
    | '/photos'
    | '/schedule'
    | '/checkout/success'
    | '/packages/$slug'
    | '/tournament/$slug'
    | '/packages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/join'
    | '/about'
    | '/archive'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/partners'
    | '/photos'
    | '/schedule'
    | '/'
    | '/checkout/success'
    | '/packages/$slug'
    | '/tournament/$slug'
    | '/packages'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/join'
    | '/_site/about'
    | '/_site/archive'
    | '/_site/cart'
    | '/_site/checkout'
    | '/_site/contact'
    | '/_site/partners'
    | '/_site/photos'
    | '/_site/schedule'
    | '/_site/'
    | '/_site/checkout/success'
    | '/_site/packages/$slug'
    | '/_site/tournament/$slug'
    | '/_site/packages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRoute
  JoinRoute: typeof JoinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/schedule': {
      id: '/_site/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof SiteScheduleRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/photos': {
      id: '/_site/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof SitePhotosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/partners': {
      id: '/_site/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof SitePartnersRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/checkout': {
      id: '/_site/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof SiteCheckoutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cart': {
      id: '/_site/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof SiteCartRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/archive': {
      id: '/_site/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof SiteArchiveRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/packages/': {
      id: '/_site/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof SitePackagesIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tournament/$slug': {
      id: '/_site/tournament/$slug'
      path: '/tournament/$slug'
      fullPath: '/tournament/$slug'
      preLoaderRoute: typeof SiteTournamentSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/packages/$slug': {
      id: '/_site/packages/$slug'
      path: '/packages/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof SitePackagesSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/checkout/success': {
      id: '/_site/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof SiteCheckoutSuccessRouteImport
      parentRoute: typeof SiteCheckoutRoute
    }
  }
}

interface SiteCheckoutRouteChildren {
  SiteCheckoutSuccessRoute: typeof SiteCheckoutSuccessRoute
}

const SiteCheckoutRouteChildren: SiteCheckoutRouteChildren = {
  SiteCheckoutSuccessRoute: SiteCheckoutSuccessRoute,
}

const SiteCheckoutRouteWithChildren = SiteCheckoutRoute._addFileChildren(
  SiteCheckoutRouteChildren,
)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteArchiveRoute: typeof SiteArchiveRoute
  SiteCartRoute: typeof SiteCartRoute
  SiteCheckoutRoute: typeof SiteCheckoutRouteWithChildren
  SiteContactRoute: typeof SiteContactRoute
  SitePartnersRoute: typeof SitePartnersRoute
  SitePhotosRoute: typeof SitePhotosRoute
  SiteScheduleRoute: typeof SiteScheduleRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SitePackagesSlugRoute: typeof SitePackagesSlugRoute
  SiteTournamentSlugRoute: typeof SiteTournamentSlugRoute
  SitePackagesIndexRoute: typeof SitePackagesIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteArchiveRoute: SiteArchiveRoute,
  SiteCartRoute: SiteCartRoute,
  SiteCheckoutRoute: SiteCheckoutRouteWithChildren,
  SiteContactRoute: SiteContactRoute,
  SitePartnersRoute: SitePartnersRoute,
  SitePhotosRoute: SitePhotosRoute,
  SiteScheduleRoute: SiteScheduleRoute,
  SiteIndexRoute: SiteIndexRoute,
  SitePackagesSlugRoute: SitePackagesSlugRoute,
  SiteTournamentSlugRoute: SiteTournamentSlugRoute,
  SitePackagesIndexRoute: SitePackagesIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRoute,
  JoinRoute: JoinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
